### ISSUE TITLE
multicore mode with logging does not seem to log warning anymore

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/parallelMap#33]
The problem is here:

```
library(parallel)

f = function(i) {
  zz = file("/home/bischl/cos/parallelMap/all.Rout", open = "wt")
  sink(zz)
  sink(zz, type = "message")
  print(588)
  message("sdfsd")
  warning("www3434")
}

y = mcmapply(f, 1:2, mc.cores = 2L)
print(y)
```

This does not log the warning. If you run this without mcmapply it works.

This worked before and broke one of our unit tests which I disabled, with a FIXME

I am now under 

R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.04

**Comment by pat-s** [comment]
4 years old, I'll labedl it as stale until a reprex proofs the issue is still valid
