### ISSUE TITLE
add parallelReplicate

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/parallelMap#38]

**Comment by berndbischl** [comment]
add a PR if you want this, pls

**Comment by jakob-r** [comment]
Looking into `parallelMap.R` I might stay with the dirty way
```r
n = 1000
parallelMap(function(rep.vec, ...) fn(...), rep.vec = rep(TRUE, n))
```
I don't know if a clean implementation is worth the effort.

* It's worth the effort? --> Tell me and keep it open
* The hack is fine and should be the base of `parallelReplicate`? --> Tell me and keep open  
* otherwise --> close

**Comment by pat-s** [comment]
Looks like it was not worth the effort :)
