### ISSUE TITLE
Feature request : Warning message on wrong order of parallelLibrary

### ISSUE THREAD

**Issue by Masutani** [mlr-org/parallelMap#61]
I have stupidly mistake to order library/source import and start.
wrong  :
  parallelLibrary/parallelSource
  parallelStart
correct : 
  parallelStart
  parallelLibrary/parallelSource
Some warning message would be helpful for such novice user.

**Comment by pat-s** [comment]
You need to solve this issue on your side. We cannot check the order of execution of certain functions on our end.
