### ISSUE TITLE
RMPISNOW and parallelMap

### ISSUE THREAD

**Issue by chrisraab** [mlr-org/parallelMap#63]
Hi parallelMap team,

thanks for the great work! I am using _parallelMap_ with _mlr_ on an HPC infrastructure but struggled to get my code to run properly. With our support I figured out, that I need to start my R session with _RMPISNOW_ and not _mpirun_. 

We tried to use 

```
cluster <- getMPIcluster()
setDefaultClusterOptions(cl = cluster)
```

in order to use the processes started with _RMPISNOW_. However, line 180-181 in [1] 

```
cl = makeCluster(spec = cpus, type = "MPI", ...)
setDefaultCluster(cl) 
```

overwrites this argument. Hence, an infinite amount of processes are spawn across the HPC. It looks like _parallelMap_ package builds the "_makeCluster_" call in such a way that the already existing cluster built by _mpirun.lsf RMPISNOW_ isn't being reused.

Finally, we ended up changing the source code of [1] in line 180-181 to

```
cl <- getMPIcluster()
setDefaultCluster(cl) 
```

After I reinstalled the changed package version, the parallelization works fine on our HPC. 

Do you see a possibility to include an option into _parallelMap_ where the use of _RMPISNOW_ is possible?

Kind regards
Christoph

[1] https://github.com/berndbischl/parallelMap/blob/master/R/parallelStart.R

**Comment by pat-s** [comment]
Can you help us with some more details about what the differences are between `getMPICluster/()` and `makeCluster()`?
