### ISSUE TITLE
throw an error in parallelStartMulticore() and parallelMap() [in multicore mode] if java is loaded

### ISSUE THREAD

**Issue by mb706** [mlr-org/parallelMap#66]
If the java-vm is loaded then [multicore-]parallelMap() will just silently crash the session without any indication of what is happening. I think if you look in the github analytics the java+mlr+parallelMap problem is somewhere among the most searched ones. Showing a visible error would probably save many users a lot of time and grief. Since the R session is essentially tainted as soon java is loaded (it cannot be unloaded easily as far as I'm aware*) the error can already be thrown in parallelStartMulticore(). Maybe give an optional `ignore.java` argument for whatever circumstances the user might need this.

\* If I'm wrong here then an alternative may be to unload java in parallelMap(), but that could have its own problems.

**Comment by jakob-r** [comment]
> I think if you look in the github analytics the java+mlr+parallelMap problem is somewhere among the most searched ones

Just out of curiosity: Where can I find this?

Otherwise: +1

**Comment by mb706** [comment]
I was referring to the mlr traffic (Insights tab -> Traffic -> Popular Content), although checking it now this seems no longer to be the case. I think I remember at one point https://github.com/mlr-org/mlr/issues/1802 was listed as popular link.

**Comment by pat-s** [comment]
Thanks, too niche to fix I'd say. People searching for it might find this issue then.
