### ISSUE TITLE
windows path problem when install package in Rstudio

### ISSUE THREAD

**Issue by yaoyao1573** [mlr-org/parallelMap#68]
I use Windows 10 system, and when I install this package in Rstudio, warnings always came out.
``` 
Warning in install.packages :
  running command '"D:/Program Files (x86)/R-3.4.3/bin/x64/R" CMD INSTALL -l "D:\Program Files (x86)\R-3.4.3\library" C:\Users\yaoyao LIU\AppData\Local\Temp\Rtmp8A0uoy/downloaded_packages/parallelMap_1.4.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘parallelMap’ had non-zero exit status
```

I think this is caused by a space in the path `C:\Users\yaoyao LIU\AppData\...` 
But this does not happen when I installed other R packages.
Could you help me with this? Or give me any suggestions ? Thanks

**Comment by jakob-r** [comment]
Can you paste the complete installation log? and also a `sessionInfo()`. Thanks

**Comment by yaoyao1573** [comment]
Hi, thank you so much for your reply~

```
> install.packages("parallelMap", lib="D:/Program Files (x86)/R-3.4.3/library")

  There is a binary version available but the source version is later:
            binary source needs_compilation
parallelMap    1.3    1.4             FALSE

installing the source package ‘parallelMap’

trying URL 'https://cran.rstudio.com/src/contrib/parallelMap_1.4.tar.gz'
Content type 'application/x-gzip' length 25650 bytes (25 KB)
downloaded 25 KB

Warning: 程辑包无效. 'C:\Users\yaoyao'
Warning: 程辑包无效. 'LIU\AppData\Local\Temp\RtmpsbyuPj/downloaded_packages/parallelMap_1.4.tar.gz'
错误: 错误：没有设定程序包
In R CMD INSTALL
Warning in install.packages :
  running command '"D:/Program Files (x86)/R-3.4.3/bin/x64/R" CMD INSTALL -l "D:\Program Files (x86)\R-3.4.3\library" C:\Users\yaoyao LIU\AppData\Local\Temp\RtmpsbyuPj/downloaded_packages/parallelMap_1.4.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘parallelMap’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\yaoyao LIU\AppData\Local\Temp\RtmpsbyuPj\downloaded_packages’
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3   
> 
```
Sorry that some of them are in Chinese, not English, and they means "invalid"

**Comment by jakob-r** [comment]
It looks like there is a problem, when a package is installed from source. It should happen to all packages, that have a newer source version then the binary version. I don't know how to solve this problem other then installing the source form a path without spaces probably.

Unfortunately the Packlage is not available for your kind of old R version as a binary version. So you either have to update R or fix the installation process. Try the following 
`install.packages("parallelMap", lib="D:/Program Files (x86)/R-3.4.3/library", destdir = "D:/")`
Afterwards you probably have to remove the package file from D:/

**Comment by pat-s** [comment]
IIRC binaries are only available for the last 2 minor R versions.
I do not think that it is worth the effort of digging deeper here.

Either update your R version or remove the spaces from the path.
If this does not help, check that have you installed the appropriate version of RTools to compile pkgs from source.
